# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import dirac_live_pb2 as dirac__live__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = "1.67.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in dirac_live_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class EndpointDeviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeviceInfo = channel.unary_unary(
            "/dio.endpoint.EndpointDevice/GetDeviceInfo",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=dirac__live__pb2.DeviceInfo.FromString,
            _registered_method=True,
        )
        self.GetSlotInfo = channel.unary_unary(
            "/dio.endpoint.EndpointDevice/GetSlotInfo",
            request_serializer=dirac__live__pb2.SlotInfoIndex.SerializeToString,
            response_deserializer=dirac__live__pb2.SlotInfo.FromString,
            _registered_method=True,
        )
        self.GetActiveSlot = channel.unary_unary(
            "/dio.endpoint.EndpointDevice/GetActiveSlot",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=dirac__live__pb2.SlotInfoIndex.FromString,
            _registered_method=True,
        )
        self.SetActiveSlot = channel.unary_unary(
            "/dio.endpoint.EndpointDevice/SetActiveSlot",
            request_serializer=dirac__live__pb2.SlotInfoIndex.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.GetOperationMode = channel.unary_unary(
            "/dio.endpoint.EndpointDevice/GetOperationMode",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=dirac__live__pb2.OperationMode.FromString,
            _registered_method=True,
        )
        self.SetOperationMode = channel.unary_unary(
            "/dio.endpoint.EndpointDevice/SetOperationMode",
            request_serializer=dirac__live__pb2.OperationMode.SerializeToString,
            response_deserializer=dirac__live__pb2.OperationMode.FromString,
            _registered_method=True,
        )


class EndpointDeviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDeviceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSlotInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetActiveSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetActiveSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetOperationMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetOperationMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EndpointDeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetDeviceInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetDeviceInfo,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=dirac__live__pb2.DeviceInfo.SerializeToString,
        ),
        "GetSlotInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetSlotInfo,
            request_deserializer=dirac__live__pb2.SlotInfoIndex.FromString,
            response_serializer=dirac__live__pb2.SlotInfo.SerializeToString,
        ),
        "GetActiveSlot": grpc.unary_unary_rpc_method_handler(
            servicer.GetActiveSlot,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=dirac__live__pb2.SlotInfoIndex.SerializeToString,
        ),
        "SetActiveSlot": grpc.unary_unary_rpc_method_handler(
            servicer.SetActiveSlot,
            request_deserializer=dirac__live__pb2.SlotInfoIndex.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "GetOperationMode": grpc.unary_unary_rpc_method_handler(
            servicer.GetOperationMode,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=dirac__live__pb2.OperationMode.SerializeToString,
        ),
        "SetOperationMode": grpc.unary_unary_rpc_method_handler(
            servicer.SetOperationMode,
            request_deserializer=dirac__live__pb2.OperationMode.FromString,
            response_serializer=dirac__live__pb2.OperationMode.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "dio.endpoint.EndpointDevice", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "dio.endpoint.EndpointDevice", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class EndpointDevice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDeviceInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/dio.endpoint.EndpointDevice/GetDeviceInfo",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            dirac__live__pb2.DeviceInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSlotInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/dio.endpoint.EndpointDevice/GetSlotInfo",
            dirac__live__pb2.SlotInfoIndex.SerializeToString,
            dirac__live__pb2.SlotInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetActiveSlot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/dio.endpoint.EndpointDevice/GetActiveSlot",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            dirac__live__pb2.SlotInfoIndex.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetActiveSlot(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/dio.endpoint.EndpointDevice/SetActiveSlot",
            dirac__live__pb2.SlotInfoIndex.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetOperationMode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/dio.endpoint.EndpointDevice/GetOperationMode",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            dirac__live__pb2.OperationMode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetOperationMode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/dio.endpoint.EndpointDevice/SetOperationMode",
            dirac__live__pb2.OperationMode.SerializeToString,
            dirac__live__pb2.OperationMode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
